// Dataset des personnages Bleach pour Bleachdle.
// Chargé comme script classique (pas de build) : expose la constante globale CHARACTERS.
//
// Champs de chaque personnage :
//   name                  : nom affiché (aussi utilisé pour l'autocomplete)
//   race                  : string[] (comparaison tri-state : vert / orange / rouge)
//   affiliation           : string[] (comparaison tri-state : vert / orange / rouge)
//   gender                : "Homme" | "Femme"
//   status                : "Vivant" | "Mort" | "Inconnu"
//   location              : lieu principal associé au personnage ("Monde Humain", "Soul Society",
//                           "Hueco Mundo", "Silbern", "Palais Royal") — reflète l'état de fin de
//                           série/épilogue (ex : Kensei et Shinji redeviennent capitaines en Soul
//                           Society après la guerre, Aizen est emprisonné en Soul Society)
//   ageBracket            : tranche d'âge fixe, voir AGE_BRACKET_ORDER dans game.js
//                           ("10-20 ans" < "20-50 ans" < "50-100 ans" < "100-150 ans" <
//                           "150-1000 ans" < "1000+ ans"). L'âge réel de la plupart des
//                           Shinigami/Arrancar adultes n'est jamais documenté (leur apparence ne
//                           reflète pas leur âge réel), donc chacun est classé dans la tranche la
//                           plus honnête possible plutôt qu'un chiffre inventé ; quand un âge
//                           minimum est explicitement confirmé dans l'histoire (ex : Yamamoto,
//                           Yhwach), le personnage est placé dans la tranche correspondante.
//   rank                  : number | null — numéro d'escouade (Gotei 13) ou d'Espada. Reflète le
//                           poste le plus notable/final du personnage (ex : un ancien capitaine
//                           garde son numéro d'escouade même s'il n'est plus en poste), sinon null
//   powerType             : type de pouvoir/arme
//   bankaiOrResurreccion  : "Oui" seulement si montré/nommé dans l'histoire, "Non" si Shinigami/
//                           Arrancar sans (ou jamais révélé à l'écran), "N/A" si non applicable
//   height                : taille en cm
//   firstArc              : arc de première apparition (voir ARC_ORDER dans game.js)
//   hairColor             : couleur de cheveux
//
// Dataset vérifié par recherche web croisée, puis par un scrape local du Bleach Fandom Wiki
// (infobox officielles) fourni par l'utilisateur — bien plus fiable que la première passe.
// Certains champs (taille, rang, Bankai/Resurrección) ont été recorrigés sur cette base ; les
// valeurs restant incertaines (ex. âges non documentés) sont volontairement représentées comme
// des plages plutôt que des chiffres inventés.

const CHARACTERS = [
  { name: "Ichigo Kurosaki", race: ["Humain", "Shinigami", "Hollow", "Quincy"], affiliation: ["Groupe de Karakura"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 174, firstArc: "Agent des Shinigami", hairColor: "Orange" },
  { name: "Rukia Kuchiki", race: ["Shinigami"], affiliation: ["Gotei 13", "Clan Kuchiki"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 13, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 144, firstArc: "Agent des Shinigami", hairColor: "Noir" },
  { name: "Renji Abarai", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 6, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 188, firstArc: "Soul Society", hairColor: "Rouge" },
  { name: "Orihime Inoue", race: ["Humain"], affiliation: ["Groupe de Karakura"], gender: "Femme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Shun Shun Rikka", bankaiOrResurreccion: "N/A", height: 157, firstArc: "Agent des Shinigami", hairColor: "Orange" },
  { name: "Yasutora Sado", race: ["Humain", "Fullbringer"], affiliation: ["Groupe de Karakura"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Fullbring", bankaiOrResurreccion: "N/A", height: 197, firstArc: "Agent des Shinigami", hairColor: "Brun" },
  { name: "Uryū Ishida", race: ["Humain", "Quincy"], affiliation: ["Quincy", "Sternritter"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Arc Quincy", bankaiOrResurreccion: "N/A", height: 171, firstArc: "Agent des Shinigami", hairColor: "Noir" },
  { name: "Kisuke Urahara", race: ["Humain", "Shinigami"], affiliation: ["Magasin Urahara", "Gotei 13"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "150-1000 ans", rank: 12, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 183, firstArc: "Agent des Shinigami", hairColor: "Blond" },
  { name: "Yoruichi Shihōin", race: ["Shinigami"], affiliation: ["Onmitsukidō", "Gotei 13"], gender: "Femme", status: "Vivant", location: "Monde Humain", ageBracket: "150-1000 ans", rank: 2, powerType: "Hakuda", bankaiOrResurreccion: "Non", height: 156, firstArc: "Agent des Shinigami", hairColor: "Violet" },
  { name: "Kenpachi Zaraki", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 11, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 202, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Byakuya Kuchiki", race: ["Shinigami"], affiliation: ["Gotei 13", "Clan Kuchiki"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 6, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 180, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Tōshirō Hitsugaya", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "50-100 ans", rank: 10, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 134, firstArc: "Soul Society", hairColor: "Blanc" },
  { name: "Rangiku Matsumoto", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 10, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 172, firstArc: "Soul Society", hairColor: "Blond" },
  { name: "Ikkaku Madarame", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 11, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 182, firstArc: "Soul Society", hairColor: "Aucun" },
  { name: "Yumichika Ayasegawa", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 11, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 169, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Jūshirō Ukitake", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Mort", location: "Soul Society", ageBracket: "150-1000 ans", rank: 13, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 187, firstArc: "Soul Society", hairColor: "Blanc" },
  { name: "Shunsui Kyōraku", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 1, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 192, firstArc: "Soul Society", hairColor: "Châtain" },
  { name: "Genryūsai Yamamoto", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Mort", location: "Soul Society", ageBracket: "1000+ ans", rank: 1, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 168, firstArc: "Soul Society", hairColor: "Aucun" },
  { name: "Sōsuke Aizen", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 5, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 186, firstArc: "Soul Society", hairColor: "Brun" },
  { name: "Gin Ichimaru", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Mort", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 3, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 185, firstArc: "Soul Society", hairColor: "Argenté" },
  { name: "Kaname Tōsen", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Mort", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 9, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 176, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Grimmjow Jaegerjaquez", race: ["Arrancar"], affiliation: ["Espada"], gender: "Homme", status: "Vivant", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 6, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 186, firstArc: "Hueco Mundo", hairColor: "Bleu" },
  { name: "Ulquiorra Cifer", race: ["Arrancar"], affiliation: ["Espada"], gender: "Homme", status: "Mort", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 4, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 169, firstArc: "Hueco Mundo", hairColor: "Noir" },
  { name: "Nnoitra Gilga", race: ["Arrancar"], affiliation: ["Espada"], gender: "Homme", status: "Mort", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 5, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 215, firstArc: "Hueco Mundo", hairColor: "Noir" },
  { name: "Nelliel Tu Odelschwanck", race: ["Arrancar"], affiliation: ["Espada"], gender: "Femme", status: "Vivant", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 3, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 176, firstArc: "Hueco Mundo", hairColor: "Vert" },
  { name: "Coyote Starrk", race: ["Arrancar"], affiliation: ["Espada"], gender: "Homme", status: "Mort", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 1, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 187, firstArc: "Hueco Mundo", hairColor: "Brun" },
  { name: "Tier Halibel", race: ["Arrancar"], affiliation: ["Espada"], gender: "Femme", status: "Vivant", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 3, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 175, firstArc: "Hueco Mundo", hairColor: "Blond" },
  { name: "Kensei Muguruma", race: ["Shinigami"], affiliation: ["Gotei 13", "Vizards"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 9, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 179, firstArc: "Hueco Mundo", hairColor: "Gris" },
  { name: "Shinji Hirako", race: ["Shinigami"], affiliation: ["Gotei 13", "Vizards"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 5, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 176, firstArc: "Hueco Mundo", hairColor: "Blond" },
  { name: "Love Aikawa", race: ["Shinigami"], affiliation: ["Vizards"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "150-1000 ans", rank: 7, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 189, firstArc: "Hueco Mundo", hairColor: "Noir" },
  { name: "Hiyori Sarugaki", race: ["Shinigami"], affiliation: ["Vizards"], gender: "Femme", status: "Vivant", location: "Monde Humain", ageBracket: "150-1000 ans", rank: 12, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 133, firstArc: "Hueco Mundo", hairColor: "Blond" },
  { name: "Rojūrō Otoribashi", race: ["Shinigami"], affiliation: ["Gotei 13", "Vizards"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 3, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 190, firstArc: "Hueco Mundo", hairColor: "Blond" },
  { name: "Mashiro Kuna", race: ["Shinigami"], affiliation: ["Gotei 13", "Vizards"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 9, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 154, firstArc: "Hueco Mundo", hairColor: "Vert" },
  { name: "Lisa Yadōmaru", race: ["Shinigami"], affiliation: ["Gotei 13", "Vizards"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 8, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 165, firstArc: "Hueco Mundo", hairColor: "Noir" },
  { name: "Hachigen Ushōda", race: ["Shinigami"], affiliation: ["Vizards"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "150-1000 ans", rank: null, powerType: "Kidō", bankaiOrResurreccion: "N/A", height: 260, firstArc: "Hueco Mundo", hairColor: "Aucun" },
  { name: "Sajin Komamura", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Mort", location: "Soul Society", ageBracket: "150-1000 ans", rank: 7, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 288, firstArc: "Soul Society", hairColor: "Brun" },
  { name: "Retsu Unohana", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Femme", status: "Mort", location: "Soul Society", ageBracket: "1000+ ans", rank: 4, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 159, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Isane Kotetsu", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 4, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 187, firstArc: "Soul Society", hairColor: "Argenté" },
  { name: "Mayuri Kurotsuchi", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 12, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 174, firstArc: "Soul Society", hairColor: "Bleu" },
  { name: "Nemu Kurotsuchi", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 12, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 167, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Sui-Feng", race: ["Shinigami"], affiliation: ["Gotei 13", "Onmitsukidō"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 2, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 150, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Yhwach", race: ["Quincy"], affiliation: ["Sternritter"], gender: "Homme", status: "Mort", location: "Silbern", ageBracket: "1000+ ans", rank: null, powerType: "Pouvoir du Roi Quincy", bankaiOrResurreccion: "N/A", height: 200, firstArc: "Guerre Sanglante des Mille Ans", hairColor: "Noir" },
  { name: "Jugram Haschwalth", race: ["Quincy"], affiliation: ["Sternritter"], gender: "Homme", status: "Inconnu", location: "Silbern", ageBracket: "1000+ ans", rank: null, powerType: "Arc Quincy", bankaiOrResurreccion: "N/A", height: 189, firstArc: "Guerre Sanglante des Mille Ans", hairColor: "Blanc" },
  { name: "Bazz-B", race: ["Quincy"], affiliation: ["Sternritter"], gender: "Homme", status: "Mort", location: "Silbern", ageBracket: "1000+ ans", rank: null, powerType: "Arc Quincy", bankaiOrResurreccion: "N/A", height: 179, firstArc: "Guerre Sanglante des Mille Ans", hairColor: "Roux" },
  { name: "Momo Hinamori", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 5, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 151, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Yachiru Kusajishi", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 11, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 109, firstArc: "Soul Society", hairColor: "Rose" },
  { name: "Kūkaku Shiba", race: ["Shinigami"], affiliation: ["Clan Shiba"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: null, powerType: "Kidō explosif", bankaiOrResurreccion: "N/A", height: 168, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Isshin Kurosaki", race: ["Humain", "Shinigami"], affiliation: ["Groupe de Karakura", "Gotei 13", "Clan Shiba"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "20-50 ans", rank: 10, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 186, firstArc: "Agent des Shinigami", hairColor: "Noir" },
  { name: "Ryūken Ishida", race: ["Humain", "Quincy"], affiliation: ["Quincy"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "20-50 ans", rank: null, powerType: "Arc Quincy", bankaiOrResurreccion: "N/A", height: 178, firstArc: "Guerre d'Hiver", hairColor: "Blanc" },
  { name: "Kūgo Ginjō", race: ["Humain", "Fullbringer"], affiliation: ["Xcution"], gender: "Homme", status: "Mort", location: "Monde Humain", ageBracket: "20-50 ans", rank: null, powerType: "Fullbring", bankaiOrResurreccion: "N/A", height: 187, firstArc: "Pouvoir Perdu", hairColor: "Noir" },
  { name: "Riruka Dokugamine", race: ["Humain", "Fullbringer"], affiliation: ["Xcution"], gender: "Femme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Fullbring", bankaiOrResurreccion: "N/A", height: 156, firstArc: "Pouvoir Perdu", hairColor: "Rose" },
  { name: "Zommari Leroux", race: ["Arrancar"], affiliation: ["Espada"], gender: "Homme", status: "Mort", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 7, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 196, firstArc: "Hueco Mundo", hairColor: "Noir" },
  { name: "Szayelaporro Granz", race: ["Arrancar"], affiliation: ["Espada"], gender: "Homme", status: "Mort", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 8, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 185, firstArc: "Hueco Mundo", hairColor: "Rose" },
  { name: "Yammy Llargo", race: ["Arrancar"], affiliation: ["Espada"], gender: "Homme", status: "Mort", location: "Hueco Mundo", ageBracket: "150-1000 ans", rank: 0, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 230, firstArc: "Hueco Mundo", hairColor: "Noir" },
  { name: "Askin Nakk Le Vaar", race: ["Quincy"], affiliation: ["Sternritter"], gender: "Homme", status: "Mort", location: "Silbern", ageBracket: "20-50 ans", rank: null, powerType: "Arc Quincy", bankaiOrResurreccion: "N/A", height: 187, firstArc: "Guerre Sanglante des Mille Ans", hairColor: "Noir" },
  { name: "Bambietta Basterbine", race: ["Quincy"], affiliation: ["Sternritter"], gender: "Femme", status: "Mort", location: "Silbern", ageBracket: "10-20 ans", rank: null, powerType: "Arc Quincy", bankaiOrResurreccion: "N/A", height: 156, firstArc: "Guerre Sanglante des Mille Ans", hairColor: "Noir" },
  { name: "Candice Catnipp", race: ["Quincy"], affiliation: ["Sternritter"], gender: "Femme", status: "Vivant", location: "Silbern", ageBracket: "10-20 ans", rank: null, powerType: "Arc Quincy", bankaiOrResurreccion: "N/A", height: 166, firstArc: "Guerre Sanglante des Mille Ans", hairColor: "Vert clair" },
  { name: "Liltotto Lamperd", race: ["Quincy"], affiliation: ["Sternritter"], gender: "Femme", status: "Vivant", location: "Silbern", ageBracket: "10-20 ans", rank: null, powerType: "Arc Quincy", bankaiOrResurreccion: "N/A", height: 149, firstArc: "Guerre Sanglante des Mille Ans", hairColor: "Rose" },
  { name: "Giselle Gewelle", race: ["Quincy"], affiliation: ["Sternritter"], gender: "Femme", status: "Vivant", location: "Silbern", ageBracket: "10-20 ans", rank: null, powerType: "Arc Quincy", bankaiOrResurreccion: "N/A", height: 160, firstArc: "Guerre Sanglante des Mille Ans", hairColor: "Noir" },
  { name: "Izuru Kira", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 3, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 173, firstArc: "Soul Society", hairColor: "Blond" },
  { name: "Shūhei Hisagi", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 9, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 181, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Marechiyo Ōmaeda", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 2, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 210, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Nanao Ise", race: ["Shinigami"], affiliation: ["Gotei 13"], gender: "Femme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: 1, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 160, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Kaien Shiba", race: ["Shinigami"], affiliation: ["Gotei 13", "Clan Shiba"], gender: "Homme", status: "Mort", location: "Soul Society", ageBracket: "150-1000 ans", rank: 13, powerType: "Zanpakutō", bankaiOrResurreccion: "Non", height: 183, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Ganju Shiba", race: ["Shinigami"], affiliation: ["Clan Shiba"], gender: "Homme", status: "Vivant", location: "Soul Society", ageBracket: "150-1000 ans", rank: null, powerType: "Combat rapproché", bankaiOrResurreccion: "N/A", height: 182, firstArc: "Soul Society", hairColor: "Noir" },
  { name: "Karin Kurosaki", race: ["Humain"], affiliation: ["Groupe de Karakura"], gender: "Femme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Pouvoir spirituel latent", bankaiOrResurreccion: "N/A", height: 137, firstArc: "Agent des Shinigami", hairColor: "Noir" },
  { name: "Yuzu Kurosaki", race: ["Humain"], affiliation: ["Groupe de Karakura"], gender: "Femme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Aucun pouvoir notable", bankaiOrResurreccion: "N/A", height: 137, firstArc: "Agent des Shinigami", hairColor: "Châtain clair" },
  { name: "Keigo Asano", race: ["Humain"], affiliation: ["Groupe de Karakura"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Aucun pouvoir notable", bankaiOrResurreccion: "N/A", height: 172, firstArc: "Agent des Shinigami", hairColor: "Brun" },
  { name: "Mizuiro Kojima", race: ["Humain"], affiliation: ["Groupe de Karakura"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Aucun pouvoir notable", bankaiOrResurreccion: "N/A", height: 160, firstArc: "Agent des Shinigami", hairColor: "Noir" },
  { name: "Tatsuki Arisawa", race: ["Humain"], affiliation: ["Groupe de Karakura"], gender: "Femme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Pouvoir spirituel latent", bankaiOrResurreccion: "N/A", height: 155, firstArc: "Agent des Shinigami", hairColor: "Noir" },
  { name: "Chizuru Honshō", race: ["Humain"], affiliation: ["Groupe de Karakura"], gender: "Femme", status: "Vivant", location: "Monde Humain", ageBracket: "10-20 ans", rank: null, powerType: "Aucun pouvoir notable", bankaiOrResurreccion: "N/A", height: 161, firstArc: "Agent des Shinigami", hairColor: "Roux" },
  { name: "Tessai Tsukabishi", race: ["Shinigami"], affiliation: ["Magasin Urahara", "Gotei 13"], gender: "Homme", status: "Vivant", location: "Monde Humain", ageBracket: "150-1000 ans", rank: null, powerType: "Kidō", bankaiOrResurreccion: "Non", height: 200, firstArc: "Agent des Shinigami", hairColor: "Noir" },
  { name: "Ichibē Hyōsube", race: ["Shinigami"], affiliation: ["Garde Royale"], gender: "Homme", status: "Vivant", location: "Palais Royal", ageBracket: "1000+ ans", rank: null, powerType: "Zanpakutō", bankaiOrResurreccion: "Oui", height: 181, firstArc: "Guerre Sanglante des Mille Ans", hairColor: "Noir" },
];
